# nicholasss alacritty config

[general]
import = ["~/.config/alacritty/themes/tokyo-night.toml"]

[window]
dimensions = { columns = 90, lines = 30 }
dynamic_title = true
# resize_increments = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 15
