# nicholasss alacritty config

# Theming
[general]
import = ["~/.config/alacritty/themes/tokyo-night.toml"]

# Default window size
[window]
dimensions = { columns = 90, lines = 30 }
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 15
